const getCountry = () => {
  let data = `<option value='CN'>China 中国
<option value='AF'>Afghanistan 阿富汗
<option value='AL'>Albania 阿尔巴尼亚
<option value='AD'>Andorra 安道尔
<option value='AO'>Angola 安哥拉
<option value='AI'>Anguilla 安圭拉
<option value='AQ'>Antarctica 南极洲
<option value='AG'>ANtigua and Barbuda 安提瓜和巴布达
<option value='AR'>Argentina 阿根廷
<option value='AM'>Armenia 亚美尼亚
<option value='AW'>Aruba 阿鲁巴
<option value='AU'>Australia 澳大利亚
<option value='AT'>Austria 奥地利
<option value='AZ'>Azerbaijan 阿塞拜疆
<option value='AE'>United Arab Emirates 阿拉伯联合酋长国
<option value='BS'>Bahamas 巴哈马
<option value='BH'>Bahrain 巴林
<option value='BD'>Bangladesh 孟加拉
<option value='BB'>Barbados 巴巴多斯
<option value='BY'>Belarus 白俄罗斯
<option value='BZ'>Belize 伯利兹
<option value='BE'>Belgium 比利时
<option value='BJ'>Benin 贝宁
<option value='BM'>Bermuda 百慕大
<option value='BT'>Bhutan 不丹
<option value='BO'>Bolivia 玻利维亚
<option value='BA'>Bosnia Hercegovina 波黑
<option value='BW'>Botswana 博茨瓦纳
<option value='BV'>Bouvet Island 布维岛
<option value='BR'>Brazil 巴西
<option value='BN'>Brunei Darussalam 文莱
<option value='BG'>Bulgaria 保加利亚
<option value='BF'>Burkina Faso 布其纳法索
<option value='BI'>Burundi 布隆迪
<option value='CM'>Cameroon 喀麦隆
<option value='CA'>Canada 加拿大
<option value='CV'>Cape Verde,Republic of 佛得角
<option value='CF'>The Central African Republic 中非共和国
<option value='CL'>Chile 智利
<option value='CN'>China 中国
<option value='CX'>Christmas Island 圣诞岛
<option value='CC'>COCOS Islands 可可岛
<option value='CO'>Colombia 哥伦比亚
<option value='CH'>tzerland 瑞士
<option value='CG'>Congo 刚果
<option value='CK'>Cook Island 库克群岛
<option value='CR'>Costa rica 哥斯达黎加
 <option value='CI'>Lvory Coast 象牙海岸
<option value='CU'>Cuba 古巴
<option value='CY'>Cyprus 塞浦路斯
<option value='CZ'>Czech Republic 捷克共和国
<option value='DK'>Denmark 丹麦
<option value='DJ'>Djibouti 吉布提
<option value='DM'>Gominica 多明哥
<option value='DE'>Grmany 德国
<option value='DO'>Dominica 多米尼加
<option value='DZ'>Algeria 阿尔及利亚
<option value='EC'>Ecuador 厄瓜多尔
<option value='EG'>Egypt 埃及
<option value='EH'>West Sahara 西撒哈拉
<option value='ES'>Spain 西班牙
<option value='EE'>Estonia 爱沙尼亚
<option value='ET'>Ethiopia 埃塞俄比亚
<option value='FJ'>Fiji 斐济
<option value='FK'>Falkland Islands 福克兰群岛
<option value='FI'>Finland 芬兰
<option value='FR'>France 法国
<option value='FM'>Micronesia 密克罗尼西亚
<option value='GA'>Gabon 加蓬
<option value='GQ'>Equatorial Guinea 赤道几内亚
<option value='GF'>French Guiana 法属圭亚那
<option value='GM'>Gambia 冈比亚
<option value='GE'>Georgia 格鲁吉亚
<option value='GH'>Ghana 加纳
<option value='GI'>Gibraltar 直布罗陀
<option value='GR'>Greece 希腊
<option value='GL'>Greenland 格陵兰
<option value='GB'>United Kingdom 英国
<option value='GD'>Grenada 格林纳达
<option value='GP'>Guadeloupe 瓜德罗普
<option value='GU'>Guam 关岛
<option value='GT'>Guatemala 危地马拉
<option value='GN'>Guinea 几内亚
<option value='GW'>Guinea-Bissau 几内亚比绍
<option value='GY'>Guyana 圭亚那
<option value='HR'>Croatia 克罗地亚
<option value='HT'>Haiti 海地
<option value='HN'>Honduras 洪都拉斯
<option value='HK'>Hong Kong 中国香港
<option value='HU'>Hungary 匈牙利
<option value='IS'>Iceland 冰岛
<option value='IN'>India 印度
<option value='ID'>Indonesia 印度尼西亚
<option value='IR'>Iran 伊朗
<option value='IQ'>Iraq 伊拉克
<option value='IO'>British Indian Ocean Territory 英联邦的印度洋领域
<option value='IE'>Ireland 爱尔兰
<option value='IL'>Israel 以色列
<option value='IT'>Italy 意大利
<option value='JM'>Jamaica 牙买加
<option value='JP'>Japan 日本
<option value='JO'>Jordan 约旦
<option value='KZ'>Kazakstan 哈萨克斯坦
<option value='KE'>Kenya 肯尼亚
<option value='KI'>Kiribati 基里巴斯
<option value='KP'>North Korea 朝鲜
<option value='KR'>Korea 韩国
<option value='KH'>Cambodia 柬埔寨
<option value='KM'>Comoros 科摩罗
<option value='KW'>kuwait 科威特
<option value='KG'>Kyrgyzstan 吉尔吉斯斯坦
<option value='KY'>Cayman Islands 开曼群岛
<option value='LA'>Laos 老挝
<option value='LK'>Sri Lanka 斯里兰卡
<option value='LV'>Latvia 拉托维亚
<option value='LB'>Lebanon 黎巴嫩
<option value='LS'>Lesotho 莱索托
<option value='LR'>Liberia 利比里亚
<option value='LY'>Libya 利比亚
<option value='LI'>Liechtenstein 列支敦士登
<option value='LT'>Lithuania 立陶宛
<option value='LU'>Luxembourg 卢森堡
<option value='LC'>St. Lucia 圣卢西亚
<option value='MO'>Macao 中国澳门
<option value='MG'>Malagasy 马达加斯加
<option value='MW'>Malawi 马拉维
<option value='MY'>Malaysia 马来西亚
<option value='MV'>Maldives 马尔代夫
<option value='ML'>Mali 马里
<option value='MT'>Malta 马耳他
<option value='MH'>Marshall Islands 马绍尔群岛
<option value='MR'>Mauritania 毛里塔尼亚
<option value='MU'>Mauritius 毛里求斯
<option value='MX'>Mexico 墨西哥
<option value='MD'>Moldova 摩尔多瓦
<option value='MC'>Monaco 摩纳哥
<option value='MN'>Mongolia 蒙古
<option value='MS'>Montserrat 蒙特塞拉特
<option value='MA'>Morocco 摩洛哥
<option value='MZ'>Mozambique 莫桑比克
<option value='MM'>Burma 缅甸
<option value='MP'>Northern Mariana Islands 北马里亚那群岛
<option value='NA'>Namibia 纳米比亚
<option value='NR'>Naura 瑙鲁
<option value='NP'>Nepal 尼泊尔
<option value='NL'>Netherlands 荷兰
<option value='NT'>Neutral Zone 中立区
<option value='NC'>New Caledonia 新喀里多尼亚
<option value='NZ'>New Zealand 新西兰
<option value='NI'>Nicaragua 尼加拉瓜
<option value='NE'>Niger 尼日尔
<option value='NG'>Nigeria 尼日利亚
<option value='NU'>Niue 纽埃
<option value='NF'>Norfolk Island 诺福克岛
<option value='NO'>Norway 挪威
<option value='OM'>Oman 阿曼
<option value='PK'>Pakistan 巴基斯坦
<option value='PF'>French Polynesia 法属玻里尼西亚
<option value='PW'>Palau 帕劳
<option value='PA'>Panama 巴拿马
<option value='PG'>Papua,Territory of 巴布亚新几内亚
<option value='PY'>Paraguay 巴拉圭
<option value='PE'>Peru 秘鲁
<option value='PH'>Philippines 菲律宾
<option value='PN'>Pitcairn Islands 皮特开恩群岛
<option value='PL'>Poland 波兰
<option value='PT'>Portugal 葡萄牙
<option value='PR'>Puerto Rico 波多黎各（美）
<option value='QA'>Qatar 卡塔尔
<option value='RO'>Romania 罗马尼亚
<option value='RU'>Russia 俄罗斯联邦
<option value='RW'>Rwanda 卢旺达
<option value='SV'>El Salvador 萨尔瓦多
<option value='SH'>St.Helena 圣赫勒那
<option value='SM'>San Marino 圣马力诺
<option value='ST'>Sao Tome and Principe 圣多美与普林西比
<option value='SA'>Saudi Arabia 沙特阿拉伯
<option value='SN'>Senegal 塞内加尔
<option value='SC'>Seychelles 塞舌尔
<option value='SL'>Sierra leone 塞拉利昂
<option value='SG'>Singapore 新加坡
<option value='SK'>Slovakia 斯洛伐克
<option value='SI'>Slovene 斯洛文尼亚
<option value='SB'>Solomon Islands 所罗门群岛
<option value='SO'>Somali 索马里
<option value='SD'>Sudan 苏丹
<option value='SR'>Surinam 苏里南
<option value='SZ'>Swaziland 斯威士兰`;
  var data1 = data.replace(/<.+>/g, ""); //去除option
  let my = data1.split(/\n/); //拆分
  let list = [];
  for (let i = 0; i < my.length; i++) {
    let english = my[i].split(/[\u4e00-\u9fa5]/)[0];
    var name = my[i];
    var reg = /[\u4e00-\u9fa5]/g;
    var names = name.match(reg);
    name = names.join("");
    list.push({
      value: name,
      label: name,
    })
  }
  return list;
}
export {
  getCountry
}